import { mkdirSync, writeFileSync } from "node:fs"
import { join } from "node:path"
import type {
  ZeroClawCapabilityPolicy,
  ZeroClawDeploymentState,
  ZeroClawEffectiveCapabilitySet
} from "../types"
import { getZeroClawDeploymentsDir } from "../storage"

export interface ZeroClawDeploymentFiles {
  deploymentDir: string
  homeDir: string
  configDir: string
  configPath: string
  envPath: string
  logPath: string
  statePath: string
}

interface BuildConfigInput {
  deployment: ZeroClawDeploymentState
  policy: ZeroClawCapabilityPolicy
  effectiveCapabilities: ZeroClawEffectiveCapabilitySet
}

function quoteTomlString(value: string): string {
  return JSON.stringify(value)
}

function stringArrayToml(values: string[]): string {
  return `[${values.map((value) => quoteTomlString(value)).join(", ")}]`
}

function boolToml(value: boolean): string {
  return value ? "true" : "false"
}

function buildConfigToml(input: BuildConfigInput): string {
  const { deployment, policy, effectiveCapabilities } = input
  return `# Generated by openwork-jarvis ZeroClaw manager
workspace_dir = ${quoteTomlString(deployment.workspacePath)}
default_provider = ${quoteTomlString(deployment.modelProvider)}
default_model = ${quoteTomlString(deployment.modelName)}
default_temperature = 0.3

[gateway]
port = ${deployment.gatewayPort}
host = ${quoteTomlString(deployment.gatewayHost)}
require_pairing = true
allow_public_bind = false

[autonomy]
workspace_only = true
allow_exec = ${boolToml(effectiveCapabilities.gates.exec)}
allow_network = ${boolToml(effectiveCapabilities.gates.network)}
max_actions_per_hour = 250
max_cost_per_day_cents = 1000

[memory]
backend = "sqlite"
auto_save = true

[observability]
backend = "log"
level = "info"

[security]
audit_enabled = true
redact_secrets = true

[jarvis_policy]
mode = ${quoteTomlString(policy.mode)}
include_global_skills = ${boolToml(policy.includeGlobalSkills)}
assigned_skills = ${stringArrayToml(policy.assignedSkillIds)}
assigned_tools = ${stringArrayToml(policy.assignedToolNames)}
assigned_connectors = ${stringArrayToml(policy.assignedConnectorKeys)}
denied_tools = ${stringArrayToml(policy.deniedToolNames)}
denied_connectors = ${stringArrayToml(policy.deniedConnectorKeys)}
effective_gate_read = ${boolToml(effectiveCapabilities.gates.read)}
effective_gate_write = ${boolToml(effectiveCapabilities.gates.write)}
effective_gate_exec = ${boolToml(effectiveCapabilities.gates.exec)}
effective_gate_network = ${boolToml(effectiveCapabilities.gates.network)}
effective_gate_channel = ${boolToml(effectiveCapabilities.gates.channel)}
`
}

function buildEnvFile(input: BuildConfigInput, files: ZeroClawDeploymentFiles): string {
  const { deployment } = input
  const lines = [
    `HOME=${files.homeDir}`,
    `ZEROCLAW_PROVIDER=${deployment.modelProvider}`,
    `ZEROCLAW_MODEL=${deployment.modelName}`,
    `ZEROCLAW_WORKSPACE=${deployment.workspacePath}`,
    `ZEROCLAW_GATEWAY_PORT=${deployment.gatewayPort}`,
    `ZEROCLAW_GATEWAY_HOST=${deployment.gatewayHost}`
  ]
  return `${lines.join("\n")}\n`
}

export function getZeroClawDeploymentFiles(deploymentId: string): ZeroClawDeploymentFiles {
  const deploymentDir = join(getZeroClawDeploymentsDir(), deploymentId)
  const homeDir = join(deploymentDir, "home")
  const configDir = join(homeDir, ".zeroclaw")
  return {
    deploymentDir,
    homeDir,
    configDir,
    configPath: join(configDir, "config.toml"),
    envPath: join(deploymentDir, "runtime.env"),
    logPath: join(deploymentDir, "runtime.log"),
    statePath: join(deploymentDir, "runtime-state.json")
  }
}

export function writeZeroClawDeploymentConfig(input: BuildConfigInput): ZeroClawDeploymentFiles {
  const files = getZeroClawDeploymentFiles(input.deployment.id)
  mkdirSync(files.deploymentDir, { recursive: true })
  mkdirSync(files.homeDir, { recursive: true })
  mkdirSync(files.configDir, { recursive: true })

  writeFileSync(files.configPath, `${buildConfigToml(input).trim()}\n`, "utf-8")
  writeFileSync(files.envPath, buildEnvFile(input, files), "utf-8")
  return files
}
